### ISSUE TITLE
Build failed with an exception:  not updated to support the latest Flutter embedding (v2)

### ISSUE THREAD

**Issue by joelfunk** [transistorsoft/flutter_background_geolocation_firebase#35]
**Your Environment**
* Plugin version: 1.1.0
* Platform: Android
* OS version: Android 15
* Device manufacturer / model: Galaxy S24 / SM-S921U1
* Flutter info (`flutter info`, `flutter doctor`):

```
Doctor summary (to see all details, run flutter
doctor -v):
[√] Flutter (Channel stable, 3.29.3, on Microsoft
    Windows [Version 10.0.26100.6584], locale     
    en-US)
[√] Windows Version (11 Home 64-bit, 24H2, 2009)
[√] Android toolchain - develop for Android
    devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual  
    Studio Community 2022 17.5.1)
[!] Android Studio (version 2023.3)
    X Unable to determine bundled Java version.   
[√] Android Studio (version 2024.3)
[√] VS Code, 64-bit edition (version 1.103.2)     
[√] Connected device (4 available)
[√] Network resources
```

* Plugin config

```
      // 1.  First configure the Firebase Adapter.
      BackgroundGeolocationFirebase.configure(BackgroundGeolocationFirebaseConfig(
        locationsCollection: '/$handle/users/users/$email/location/location', // even number of segments for updateSingleDocument to work
        geofencesCollection: '/$handle/users/users/$email/location/location',
        updateSingleDocument: true
      ));
      // 2.  Configure BackgroundGeolocation as usual.
      bg.BackgroundGeolocation.onLocation((bg.Location location) {
        print('[location] $location');
      });

      bg.BackgroundGeolocation.ready(bg.Config(
        debug: false,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        locationAuthorizationRequest: 'WhenInUse',
        stopOnTerminate: true, // false for ongoing operation.
        startOnBoot: false)
      );
```

**To Reproduce**
1.  Configure plugin for use as per documentation
2.  Update to Flutter version 3.29.3
3.  Build Fails:

```
error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                  ^
  symbol:   class Registrar
  location: interface PluginRegistry
...
public static void registerWith(Registrar registrar) {
                                ^
  symbol:   class Registrar
  location: class BackgroundGeolocationFirebasePlugin
...
public static void setPluginRegistrant(PluginRegistry.PluginRegistrantCallback callback) {
                                                     ^
  symbol:   class PluginRegistrantCallback
  location: interface PluginRegistry
```

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
When I checkout Flutter version 3.24.5, it works perfectly.

**Comment by christocracy** [comment]
Looking into it.

**Comment by joelfunk** [comment]
Any progress on this issue?

**Comment by tribolumen** [comment]
I’m receiving this error in my code as well, and poked the agent to look at it. Essentially, v1 and v2 of embedding is supported in the geolocation libraries, but v1 was removed from the codebase I’m working with at 3.38.3. It’s failing because it can’t find the import code for v1. So the suggested fix is to remove the v1 support in the geolocation code to compile successfully. Instead, I’ve created a pre-compilation task to patch out the v1 code before building so I can still nab updates for the geolocation software but not manage my own fork.  

I just put this in, so I haven’t done a full test on the app, but with regards to build success, this was successful.

**Comment by christocracy** [comment]
yea, that old v1 code simply needs to be deleted.

**Comment by fixatd** [comment]
Sorry for commenting on an old ticket but did this get resolved ? I'm also getting the same error with a similar setup.

**Comment by joelfunk** [comment]
I've all but given up on this package.  Can we be clear about what we need to do to resolve this issue?  How do we "delete that old v1 code"?  Shouldn't there be an update to this library?

**Comment by fixatd** [comment]
I'm also stuck on what that meant. I've been searching the local copy of the library in case I could try deleting something but no luck.
